apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels: 
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: ericlessa/hello-go:v11_startupProbe

          resources: 
            requests: #minimo para rodar -> reservando recursos do cluster para o POD
              cpu: "0.05"
              memory: 20Mi
            limits:
              cpu: "0.05"
              memory: 25Mi

          startupProbe:
            httpGet:
              path: /readiness
              port: 8000
            periodSeconds: 3
            failureThreshold: 30

          livenessProbe:
            httpGet:
              path: /readiness
              port: 8000
            periodSeconds: 5
            failureThreshold: 1
            timeoutSeconds: 1
            successThreshold: 1
          
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8000
            periodSeconds: 3
            failureThreshold: 1

          envFrom:
           - configMapRef:
              name: goserver-env
           - secretRef:
              name: goserver-secret 
          
          volumeMounts:
            - mountPath: "/go/example"
              name: config

      volumes:
        - name: config 
          configMap: 
            name: configmap-file
            items:
              - key: helloworld
                path: "example.txt"
            